const machines=[['drum-machine','Drum Machine','🥁','#ff9f1c','beats'],['kaossilator-pro','Kaossilator Pro','🕹️','#9cff00','xy synth'],['op-1','OP-1','🎹','#eeeeee','sketchbox'],['orchid','Orchid','🌺','#b66cff','generator'],['reese','Reese','🔊','#95c744','bass'],['looping-drum-loops','Looping Drum Loops','🔁','#22d3ee','loops'],['the-choppa','The Choppa','✂️','#ff4d3d','slicer'],['sampla','Sampla','🎛️','#4aa3ff','sampler'],['launcha','Launcha','🚀','#ffd000','launcher'],['mono-station','Mono Station','〰️','#62b6ff','mono synth'],['mellotron','Mellotron','📼','#d9b985','tape'],['bit-crusher','Bit Crusher','▦','#c05cff','lo-fi'],['fm-station','FM Station','📡','#2dd4d7','fm'],['delay-station','Delay Station','⏱️','#9ccc65','delay'],['filter-station','Filter Station','◉','#f6c600','filter'],['master-fx','Master FX','✨','#b8c4d4','master fx']];
let ctx,master,delay,filter,recDest,mediaRec,chunks=[],active=machines[0],step=0,playing=false,timer=null,samples={},pattern=JSON.parse(localStorage.bgPattern||'{}');
function init(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.75;filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=18000;delay=ctx.createDelay(1);delay.delayTime.value=.22;let fb=ctx.createGain();fb.gain.value=.28;delay.connect(fb);fb.connect(delay);filter.connect(delay);filter.connect(master);delay.connect(master);recDest=ctx.createMediaStreamDestination();master.connect(ctx.destination);master.connect(recDest)}
function t(){init();if(ctx.state==='suspended')ctx.resume();return ctx.currentTime}function env(g,a=.01,d=.25,v=.45){let n=t();g.gain.setValueAtTime(.001,n);g.gain.exponentialRampToValueAtTime(v,n+a);g.gain.exponentialRampToValueAtTime(.001,n+d)}
function osc(f,type='sine',dur=.3,vol=.38){let o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=f;env(g,.01,dur,vol);o.connect(g).connect(filter);o.start();o.stop(ctx.currentTime+dur+.06)}
function noise(d=.12,v=.22,bp=6000){let b=ctx.createBuffer(1,ctx.sampleRate*d,ctx.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=Math.random()*2-1;let s=ctx.createBufferSource(),g=ctx.createGain(),f=ctx.createBiquadFilter();f.type='bandpass';f.frequency.value=bp;env(g,.004,d,v);s.buffer=b;s.connect(f).connect(g).connect(filter);s.start();s.stop(ctx.currentTime+d)}
function kick(){let o=ctx.createOscillator(),g=ctx.createGain(),n=t();o.type='sine';o.frequency.setValueAtTime(130,n);o.frequency.exponentialRampToValueAtTime(42,n+.18);env(g,.004,.3,.85);o.connect(g).connect(filter);o.start();o.stop(n+.35)}function snare(){noise(.16,.35,2300);osc(180,'triangle',.12,.14)}function hat(){noise(.055,.16,9500)}function clap(){[0,35,70].forEach(ms=>setTimeout(()=>noise(.045,.18,1800),ms))}
function chord(root=180,maj=false){[0,maj?4:3,7,12].forEach(n=>osc(root*Math.pow(2,n/12),'sawtooth',.7,.13))}function bass(f=55){osc(f,'sawtooth',.55,.55);osc(f*1.01,'sawtooth',.55,.32)}function fm(f=260,i=2){let n=t(),c=ctx.createOscillator(),m=ctx.createOscillator(),mg=ctx.createGain(),g=ctx.createGain();c.type=m.type='sine';c.frequency.value=f;m.frequency.value=f*i;mg.gain.value=120;m.connect(mg).connect(c.frequency);env(g,.01,.45,.42);c.connect(g).connect(filter);m.start();c.start();m.stop(n+.5);c.stop(n+.5)}
function playSample(i){let arr=samples[active[0]]||[];if(!arr[i])return false;let a=arr[i].cloneNode();a.currentTime=0;a.volume=.9;a.play();return true}
function play(i){init();if(playSample(i))return;let id=active[0];if(id.includes('drum')||id==='launcha'){[kick,snare,hat,clap,()=>osc(120,'triangle'),()=>noise(.05,.2,1600),()=>noise(.35,.12,7000),()=>noise(.25,.11,9000)][i%8]()}else if(id==='reese'){bass(42+i*7);filter.frequency.setTargetAtTime(450+i*300,ctx.currentTime,.02)}else if(id==='fm-station'){fm(150+i*55,1.2+i*.4)}else if(id==='kaossilator-pro'){osc(160*Math.pow(2,[0,2,3,5,7,8,10,12][i]/12),i%2?'square':'sawtooth',.35,.35)}else if(id==='the-choppa'||id==='bit-crusher'){noise(.08+i*.02,.32,900+i*850);osc(90+i*30,'square',.09,.2)}else if(id.includes('delay')){delay.delayTime.setTargetAtTime(.08+i*.06,ctx.currentTime,.03);osc(220+i*40,'triangle',.45,.3)}else if(id.includes('filter')){filter.type=i<3?'lowpass':i<6?'bandpass':'highpass';filter.frequency.setTargetAtTime(250+i*700,ctx.currentTime,.03);chord(150+i*18)}else if(id==='master-fx'){delay.delayTime.setTargetAtTime(.12+i*.05,ctx.currentTime,.03);noise(.2,.12,4000+i*400);chord(120+i*14)}else{chord(150+i*22,i%2); if(i>4)fm(220+i*35,2+i*.2)}}
function render(){document.querySelector('#machineName').textContent=active[1];document.querySelector('#machineIcon').textContent=active[2];document.documentElement.style.setProperty('--accent',active[3]);document.querySelector('#machineSub').textContent=active[4];document.querySelector('#machines').innerHTML=machines.map((m,idx)=>`<button class="machineBtn ${m[0]===active[0]?'on':''}" data-i="${idx}" style="--a:${m[3]}"><span>${m[2]}</span><b>${m[1]}</b><small>${m[4]}</small></button>`).join('');document.querySelector('#pads').innerHTML=Array.from({length:16},(_,i)=>`<button class="pad" data-pad="${i}">${i+1}</button>`).join('');document.querySelector('#steps').innerHTML=Array.from({length:16},(_,i)=>`<button class="seq ${pattern[active[0]]?.[i]?'on':''}" data-step="${i}">${i+1}</button>`).join('');document.querySelector('#status').textContent=`${active[1]} ready · pads trigger ${active[4]} · samples loaded: ${(samples[active[0]]||[]).length}`}
function tick(){document.querySelectorAll('.seq').forEach((b,i)=>b.classList.toggle('active',i===step));if(pattern[active[0]]?.[step])play(step%16);step=(step+1)%16}
function savePattern(){localStorage.bgPattern=JSON.stringify(pattern)}
document.addEventListener('click',e=>{let m=e.target.closest('.machineBtn');if(m){active=machines[+m.dataset.i];step=0;render()}let p=e.target.closest('.pad');if(p){let i=+p.dataset.pad;p.classList.add('on');play(i);setTimeout(()=>p.classList.remove('on'),120)}let s=e.target.closest('.seq');if(s){let i=+s.dataset.step;pattern[active[0]]=pattern[active[0]]||Array(16).fill(0);pattern[active[0]][i]=pattern[active[0]][i]?0:1;savePattern();s.classList.toggle('on')}});
document.querySelector('#start').onclick=()=>{init();playing=!playing;if(playing){timer=setInterval(tick,(60000/(+bpm.value||96))/4);start.textContent='STOP'}else{clearInterval(timer);start.textContent='START'}};document.querySelector('#panic').onclick=()=>{clearInterval(timer);playing=false;start.textContent='START';step=0};document.querySelector('#saveKit').onclick=()=>{localStorage.bgKit=JSON.stringify({pattern});status.textContent='kit saved locally'};document.querySelector('#loadKit').onclick=()=>{try{let k=JSON.parse(localStorage.bgKit||'{}');if(k.pattern)pattern=k.pattern;render()}catch(e){}};
document.querySelector('#sampleInput').onchange=e=>{samples[active[0]]=[...e.target.files].map(f=>{let a=new Audio(URL.createObjectURL(f));a.preload='auto';return a});render()};document.querySelector('#rec').onclick=async()=>{init();if(!mediaRec||mediaRec.state==='inactive'){chunks=[];mediaRec=new MediaRecorder(recDest.stream);mediaRec.ondataavailable=e=>chunks.push(e.data);mediaRec.onstop=()=>{let url=URL.createObjectURL(new Blob(chunks,{type:'audio/webm'}));download.href=url;download.download='beargrid-recording.webm';download.hidden=false};mediaRec.start();rec.textContent='STOP REC'}else{mediaRec.stop();rec.textContent='REC'}};
window.addEventListener('keydown',e=>{let keys='1234567890qwerty'.split('');let i=keys.indexOf(e.key.toLowerCase());if(i>-1){e.preventDefault();play(i%16)}});
if(navigator.requestMIDIAccess){navigator.requestMIDIAccess().then(a=>{for(let input of a.inputs.values())input.onmidimessage=e=>{let[d,n,v]=e.data;if(d===144&&v>0){let map={36:0,37:1,38:2,39:3,40:4,41:5,42:6,43:7,44:8,45:9,46:10,47:11,48:12,49:13,50:14,51:15};if(map[n]!==undefined)play(map[n])}}}).catch(()=>{})}
render();