const machines=[['drum-machine','Drum Machine','🥁','#ff9f1c','beats'],['kaossilator-pro','Kaossilator Pro','🕹️','#9cff00','xy synth'],['op-1','OP-1','🎹','#eeeeee','sketchbox'],['orchid','Orchid','🌺','#b66cff','generator'],['reese','Reese','🔊','#95c744','bass'],['looping-drum-loops','Looping Drum Loops','🔁','#22d3ee','loops'],['the-choppa','The Choppa','✂️','#ff4d3d','slicer'],['sampla','Sampla','🎛️','#4aa3ff','sampler'],['launcha','Launcha','🚀','#ffd000','launcher'],['mono-station','Mono Station','〰️','#62b6ff','mono synth'],['mellotron','Mellotron','📼','#d9b985','tape'],['bit-crusher','Bit Crusher','▦','#c05cff','lo-fi'],['fm-station','FM Station','📡','#2dd4d7','fm'],['delay-station','Delay Station','⏱️','#9ccc65','delay'],['filter-station','Filter Station','◉','#f6c600','filter'],['master-fx','Master FX','✨','#b8c4d4','master fx']];
const state={ctx:null,master:null,delay:null,filter:null,recDest:null,mediaRec:null,chunks:[],active:machines[0],step:0,playing:false,timer:null,samples:{},pattern:{},midi:null};
try{state.pattern=JSON.parse(localStorage.bgPattern||'{}')||{}}catch(e){state.pattern={}}
function $(s){return document.querySelector(s)}
function $all(s){return [...document.querySelectorAll(s)]}
function machineId(){return state.active[0]}
function machinePattern(){const id=machineId();if(!Array.isArray(state.pattern[id]))state.pattern[id]=Array(16).fill(0);return state.pattern[id]}
function setStatus(msg){const el=$('#status');if(el)el.textContent=msg}
function init(){if(state.ctx)return;const AC=window.AudioContext||window.webkitAudioContext;state.ctx=new AC();state.master=state.ctx.createGain();state.master.gain.value=.75;state.filter=state.ctx.createBiquadFilter();state.filter.type='lowpass';state.filter.frequency.value=18000;state.filter.Q.value=.7;state.delay=state.ctx.createDelay(1.5);state.delay.delayTime.value=.22;const fb=state.ctx.createGain();fb.gain.value=.28;state.delay.connect(fb);fb.connect(state.delay);state.filter.connect(state.delay);state.filter.connect(state.master);state.delay.connect(state.master);state.recDest=state.ctx.createMediaStreamDestination();state.master.connect(state.ctx.destination);state.master.connect(state.recDest)}
function now(){init();if(state.ctx.state==='suspended')state.ctx.resume();return state.ctx.currentTime}
function env(g,a=.01,d=.25,v=.45){const n=now();g.gain.cancelScheduledValues(n);g.gain.setValueAtTime(.001,n);g.gain.exponentialRampToValueAtTime(v,n+a);g.gain.exponentialRampToValueAtTime(.001,n+d)}
function osc(f,type='sine',dur=.3,vol=.38){const o=state.ctx.createOscillator(),g=state.ctx.createGain();o.type=type;o.frequency.value=f;env(g,.01,dur,vol);o.connect(g).connect(state.filter);o.start();o.stop(state.ctx.currentTime+dur+.06)}
function noise(d=.12,v=.22,bp=6000){const b=state.ctx.createBuffer(1,state.ctx.sampleRate*d,state.ctx.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=Math.random()*2-1;const s=state.ctx.createBufferSource(),g=state.ctx.createGain(),f=state.ctx.createBiquadFilter();f.type='bandpass';f.frequency.value=bp;env(g,.004,d,v);s.buffer=b;s.connect(f).connect(g).connect(state.filter);s.start();s.stop(state.ctx.currentTime+d)}
function kick(){const o=state.ctx.createOscillator(),g=state.ctx.createGain(),n=now();o.type='sine';o.frequency.setValueAtTime(130,n);o.frequency.exponentialRampToValueAtTime(42,n+.18);env(g,.004,.3,.85);o.connect(g).connect(state.filter);o.start();o.stop(n+.35)}
function snare(){noise(.16,.35,2300);osc(180,'triangle',.12,.14)}
function hat(){noise(.055,.16,9500)}
function clap(){[0,35,70].forEach(ms=>setTimeout(()=>noise(.045,.18,1800),ms))}
function chord(root=180,maj=false){[0,maj?4:3,7,12].forEach(n=>osc(root*Math.pow(2,n/12),'sawtooth',.7,.13))}
function bass(f=55){osc(f,'sawtooth',.55,.55);osc(f*1.01,'sawtooth',.55,.32)}
function fm(f=260,i=2){const n=now(),c=state.ctx.createOscillator(),m=state.ctx.createOscillator(),mg=state.ctx.createGain(),g=state.ctx.createGain();c.type=m.type='sine';c.frequency.value=f;m.frequency.value=f*i;mg.gain.value=120;m.connect(mg).connect(c.frequency);env(g,.01,.45,.42);c.connect(g).connect(state.filter);m.start();c.start();m.stop(n+.5);c.stop(n+.5)}
function playDecodedSample(i){const bank=state.samples[machineId()]||[];const item=bank[i];if(!item||!item.buffer)return false;const src=state.ctx.createBufferSource(),g=state.ctx.createGain();src.buffer=item.buffer;g.gain.value=.9;src.connect(g).connect(state.filter);src.start();return true}
function synthFallback(i){const id=machineId();if(id.includes('drum')||id==='launcha'){[kick,snare,hat,clap,()=>osc(120,'triangle'),()=>noise(.05,.2,1600),()=>noise(.35,.12,7000),()=>noise(.25,.11,9000)][i%8]()}else if(id==='reese'){bass(42+i*7);state.filter.frequency.setTargetAtTime(450+i*300,state.ctx.currentTime,.02)}else if(id==='fm-station'){fm(150+i*55,1.2+i*.4)}else if(id==='kaossilator-pro'){osc(160*Math.pow(2,[0,2,3,5,7,8,10,12][i%8]/12),i%2?'square':'sawtooth',.35,.35)}else if(id==='the-choppa'||id==='bit-crusher'){noise(.08+(i%8)*.02,.32,900+(i%8)*850);osc(90+i*30,'square',.09,.2)}else if(id.includes('delay')){state.delay.delayTime.setTargetAtTime(.08+(i%8)*.06,state.ctx.currentTime,.03);osc(220+i*40,'triangle',.45,.3)}else if(id.includes('filter')){state.filter.type=i<3?'lowpass':i<6?'bandpass':'highpass';state.filter.frequency.setTargetAtTime(250+i*700,state.ctx.currentTime,.03);chord(150+i*18)}else if(id==='master-fx'){state.delay.delayTime.setTargetAtTime(.12+(i%8)*.05,state.ctx.currentTime,.03);noise(.2,.12,4000+i*400);chord(120+i*14)}else{chord(150+i*22,i%2);if(i>4)fm(220+i*35,2+i*.2)}}
function flashPad(i){const pad=document.querySelector(`[data-pad="${i}"]`);if(!pad)return;pad.classList.add('on');setTimeout(()=>pad.classList.remove('on'),130)}
function triggerPad(i,{visual=true}={}){i=Number(i);if(!Number.isFinite(i))return;const pad=i%16;init();if(visual)flashPad(pad);if(!playDecodedSample(pad))synthFallback(pad);setStatus(`${state.active[1]} pad ${pad+1} fired · samples: ${(state.samples[machineId()]||[]).length}`)}
async function loadSamples(files){init();const id=machineId();const audioFiles=[...files].filter(f=>f.type.startsWith('audio/')||/\.(wav|mp3|ogg|m4a|flac)$/i.test(f.name));state.samples[id]=[];for(const file of audioFiles){try{const buf=await file.arrayBuffer();const decoded=await state.ctx.decodeAudioData(buf.slice(0));state.samples[id].push({name:file.name,buffer:decoded})}catch(e){console.warn('BearGrid sample load failed',file.name,e)}}render();setStatus(`${state.active[1]} loaded ${state.samples[id].length} sample(s)`) }
function render(){const id=machineId();$('#machineName').textContent=state.active[1];$('#machineIcon').textContent=state.active[2];document.documentElement.style.setProperty('--accent',state.active[3]);$('#machineSub').textContent=state.active[4];$('#machines').innerHTML=machines.map((m,idx)=>`<button class="machineBtn ${m[0]===id?'on':''}" data-i="${idx}" style="--a:${m[3]}"><span>${m[2]}</span><b>${m[1]}</b><small>${m[4]}</small></button>`).join('');$('#pads').innerHTML=Array.from({length:16},(_,i)=>`<button class="pad" data-pad="${i}" title="Pad ${i+1}">${i+1}</button>`).join('');const pat=machinePattern();$('#steps').innerHTML=Array.from({length:16},(_,i)=>`<button class="seq ${pat[i]?'on':''}" data-step="${i}" title="Step ${i+1}">${i+1}</button>`).join('');setStatus(`${state.active[1]} ready · pads trigger ${state.active[4]} · samples loaded: ${(state.samples[id]||[]).length}`)}
function tick(){const steps=$all('.seq');steps.forEach((b,i)=>b.classList.toggle('active',i===state.step));if(machinePattern()[state.step])triggerPad(state.step,{visual:true});state.step=(state.step+1)%16}
function savePattern(){localStorage.bgPattern=JSON.stringify(state.pattern)}
function startStop(){init();state.playing=!state.playing;if(state.playing){clearInterval(state.timer);state.timer=setInterval(tick,(60000/(+$('#bpm').value||96))/4);$('#start').textContent='STOP'}else{clearInterval(state.timer);$('#start').textContent='START'}}
function panic(){clearInterval(state.timer);state.playing=false;state.step=0;$('#start').textContent='START';$all('.seq,.pad').forEach(el=>el.classList.remove('active','on'));setStatus('panic stop · transport reset')}
function saveKit(){localStorage.bgKit=JSON.stringify({pattern:state.pattern,machine:machineId(),bpm:$('#bpm').value});setStatus('kit saved locally')}
function loadKit(){try{const k=JSON.parse(localStorage.bgKit||'{}');if(k.pattern)state.pattern=k.pattern;if(k.bpm)$('#bpm').value=k.bpm;if(k.machine){const found=machines.find(m=>m[0]===k.machine);if(found)state.active=found}render()}catch(e){setStatus('kit load failed')}}
function setupMidi(){if(!navigator.requestMIDIAccess)return;navigator.requestMIDIAccess().then(access=>{const map={36:0,37:1,38:2,39:3,40:4,41:5,42:6,43:7,44:8,45:9,46:10,47:11,48:12,49:13,50:14,51:15};for(const input of access.inputs.values()){input.onmidimessage=e=>{const[d,n,v]=e.data;if((d===144&&v>0)||d===153){if(map[n]!==undefined)triggerPad(map[n])}}}}).catch(()=>{})}
document.addEventListener('click',e=>{const m=e.target.closest('.machineBtn');if(m){state.active=machines[+m.dataset.i];state.step=0;render();return}const p=e.target.closest('.pad');if(p){triggerPad(+p.dataset.pad);return}const s=e.target.closest('.seq');if(s){const i=+s.dataset.step;const pat=machinePattern();pat[i]=pat[i]?0:1;savePattern();s.classList.toggle('on');setStatus(`${state.active[1]} step ${i+1} ${pat[i]?'on':'off'}`)}});
$('#start').onclick=startStop;$('#panic').onclick=panic;$('#saveKit').onclick=saveKit;$('#loadKit').onclick=loadKit;$('#sampleInput').onchange=e=>loadSamples(e.target.files);$('#rec').onclick=async()=>{init();if(!state.mediaRec||state.mediaRec.state==='inactive'){state.chunks=[];state.mediaRec=new MediaRecorder(state.recDest.stream);state.mediaRec.ondataavailable=e=>state.chunks.push(e.data);state.mediaRec.onstop=()=>{const url=URL.createObjectURL(new Blob(state.chunks,{type:'audio/webm'}));$('#download').href=url;$('#download').download='beargrid-recording.webm';$('#download').hidden=false};state.mediaRec.start();$('#rec').textContent='STOP REC';setStatus('recording browser output')}else{state.mediaRec.stop();$('#rec').textContent='REC';setStatus('recording ready to download')}};
window.addEventListener('keydown',e=>{if(e.target&&/input|textarea|select/i.test(e.target.tagName))return;const keys='1234567890qwerty'.split('');const i=keys.indexOf(e.key.toLowerCase());if(i>-1){e.preventDefault();triggerPad(i)}});
window.BearGridApp={state,machines,triggerPad,loadSamples,render,panic,startStop};
setupMidi();render();
